POST http://localhost:3001/api/establishment-users/sign-up
Content-Type: application/json

{
    "username": "keirthjames",
    "name": "Keirth James",
    "password": "kj123"
}

###
POST http://localhost:3001/api/establishment-users/sign-up
Content-Type: application/json

{
    "username": "robinrae",
    "name": "Robin Rae",
    "password": "salainen"
}

###
POST http://localhost:3001/api/establishment-users/sign-up
Content-Type: application/json

{
    "username": "starnex1",
    "name": "Star Nex",
    "password": "imagination"
}

###
POST http://localhost:3001/api/establishment-users/sign-up
Content-Type: application/json

{
    "name": "Star Nex",
    "password": "imagination"
}
###
POST http://localhost:3001/api/establishment-users/sign-up
Content-Type: application/json

{
    "username": "lukeandres",
    "name": "Star Nex",
    "password": "imagination"
}

