POST http://localhost:3001/api/individual-users/sign-up
Content-Type: application/json

{
    "username": "kiswired",
    "name": "Kis wired",
    "password": "kiswired000"
}

###
POST http://localhost:3001/api/individual-users/sign-up
Content-Type: application/json

{
    "username": "lukeandres",
    "name": "Luke Andres",
    "password": "salainen"
}

###
POST http://localhost:3001/api/individual-users/sign-up
Content-Type: application/json

{
    "username": "merhostnacab",
    "name": "Merho Stnacab",
    "password": "imagination"
}

###
POST http://localhost:3001/api/individual-users/sign-up
Content-Type: application/json

{
    "username": "luffytaro",
    "name": "Luffy",
    "password": "imagination"
}

###
POST http://localhost:3001/api/individual-users/sign-up
Content-Type: application/json

{
    "username": "keirthjames",
    "name": "Keirth James",
    "password": "kj123"
}

###
POST http://localhost:3001/api/individual-users/sign-up
Content-Type: application/json

{
    "name": "Luke Andres",
    "password": "salainen"
}


