PUT  http://localhost:3001/api/admin-users/62415da26c2b55551f9b5af4/change-username
Content-Type: application/json

{   
    "username": "gozaroga"
}

###
PUT  http://localhost:3001/api/admin-users/62415da26c2b55551f9b5af4/change-password
Content-Type: application/json

{
    "username": "gozaroga",
    "oldPassword": "semaj23",
    "newPassword": "realityimage"
}