PUT  http://localhost:3001/api/individual-users/6241613880f715524334f3a2/change-username
Content-Type: application/json

{
    "username": "huawei321"
}

###
PUT  http://localhost:3001/api/individual-users/6241613880f715524334f3a2/change-password
Content-Type: application/json

{
    "oldPassword": "kiswired000",
    "newPassword": "lightborn"

}
###
PUT  http://localhost:3001/api/individual-users/6241613880f715524334f3a2/change-password
Content-Type: application/json

{
    "username": "huawei321",
    "oldPassword": "kiswired000",
    "newPassword": "lightborn"

}

