POST http://localhost:3001/api/persons/sign-up
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtpc3dpcmVkIiwiaWQiOiI2MjQ0MDA1YzVjMTY4ZWIxNjdlZmM1OGEiLCJpYXQiOjE2NDg4MjE4NjV9.N6BoxA4hDr9G0ssa_ybWR2xVi2RYGMFXGEVTMxxnvYM

{
    "firstName": "asdfasdfa",
    "lastName": "Strange",
    "middleName": "Doctor",
    "suffix": "",
    "gender": "Male",
    "birthDate": "1 April 2000",
    "contactNumber": "09885667495",
    "email": "sudowoodo@gmail.com",
    "status": "Negative",
    "province": "Lanao del Norte",
    "city": "Iligan City",
    "barangay": "Tibanga",
    "street": "TransMotor St. :)",
    "resident": false,
    "special": false
}
