POST http://localhost:3001/api/admin-users/sign-up
Content-Type: application/json

{
    "name": "Anthony James",
    "password": "semaj23"
}

###
POST http://localhost:3001/api/admin-users/sign-up
Content-Type: application/json

{
    "username": "sudowoodo",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3001/api/admin-users/sign-up
Content-Type: application/json

{
    "username": "luffytaro",
    "name": "Luffy",
    "password": "imagination"
}

###
POST http://localhost:3001/api/admin-users/sign-up
Content-Type: application/json

{
    "username": "asdfsasdfadf",
    "name": "tonyo",
    "password": "imagination"
}
